version: 1

disable_existing_loggers: False 

## use formatters to cutomize your output
## add of remove parameters accordingly
##

formatters:
    custom_format:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(hostname)s ............. \n %(message)s"
    simple:
        format: "%(asctime)s -- %(message)s"
    default:
        format: "%(message)s"
    default_file:
        format:  "%(asctime)s - %(name)s - %(levelname)s - \n %(message)s"
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: default
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: upgrade.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: default_file
        filename: upgrade.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    critical_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: CRITICAL
        formatter: default_file
        filename: upgrade.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: default_file
        filename: upgrade.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: INFO 
    handlers: [console, info_file_handler]
